language: node_js
node_js:
    - "0.12"
before_script:
    - npm install -g grunt-cli
    - bower install
    - echo 'America/Los_Angeles' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
